import type { Metadata } from "next";
import "./globals.css";
import AuthBootstrap from "@/components/AuthBootstrap";
import StoreProvider from "@/store/Provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthBootstrap />
          {children}
        </StoreProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
